[profile.default]
evm_version = "cancun"
ffi = true
fs_permissions = [
    {access = "read-write", path = ".forge-snapshots/"},
    {access = "read", path = "lib/foundry-chainlink-toolkit/out"}
]
libs = ["lib"]
out = "out"
solc_version = "0.8.28"
src = "src"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
alchemy_sepolia="${ALCHEMY_SEPOLIA_RPC}"
local = "http://127.0.0.1:8545"

PRIVATE_KEY_LOCAL = "${PRIVATE_KEY_LOCAL}"
PRIVATE_KEY = "${PRIVATE_KEY}"

[etherscan]
sepolia = { key = "${SEPOLIA_API_KEY}" }